#! /bin/bash
server="192.168.30.2/Laurent/Jrdl6468"
echo "" > map.txt
echo "" > folders.txt

# srcfolder="Private.Familly.Dominique BURAIS.Envoye&AwE-s"
# dstfolder="Private.Familly.Dominique BURAIS.Envoye"
# echo "$srcfolder:$destfolder" > map.txt
# ./imapcopy.pl -v -C -R -M map.txt -S $server -D $server -m "${srcfolder}"

# Professional.Cisco Systems   (359 msgs, 65.34 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services)   (31 msgs, 1.19 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services   (323 msgs, 56.83 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.AMERICAS   (18 msgs, 3.97 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.AMERICAS.AMERICAS Archives   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.AMERICAS.AMERICAS Archives.LATAM   (705 msgs, 147.24 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.AMERICAS.AMERICAS Enterprise   (17 msgs, 5.26 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.AMERICAS.AMERICAS SP   (65 msgs, 17.27 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.AMERICAS.Archives   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.AMERICAS.Archives.LATAM   (280 msgs, 69.37 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Cisco Consulting Services   (400 msgs, 50.40 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR   (127 msgs, 20.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.EMEAR ESD   (2 msgs, 0.38 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.EMEAR SP   (161 msgs, 54.04 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Events   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Events.All Hands   (41 msgs, 12.63 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Events.Q4-11 Highlights   (36 msgs, 39.20 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives   (8 msgs, 6.35 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.FY14 Execution Plan   (113 msgs, 54.88 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.FY14 Execution Plan.B Get More Big Deals   (1 msgs, 9.01 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.FY14 Execution Plan.C Better Bid &- Deliver Complex Deals   (231 msgs, 70.86 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.FY14 Execution Plan.E Resource Planning &- Management   (188 msgs, 73.01 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.FY14 Execution Plan.F Delivery Optimization   (69 msgs, 68.33 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.FY14 Execution Plan.G Project Berlin   (580 msgs, 243.70 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.FY14 Execution Plan.H Our Talent   (1 msgs, 0.02 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.FY14 Execution Plan.X Tools to run the business   (7 msgs, 1.12 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.Lab   (1320 msgs, 140.70 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Initiatives.Operating Model   (430 msgs, 294.25 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Theatres   (89 msgs, 53.99 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Theatres.Africa &- Russia   (675 msgs, 112.71 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Theatres.Central   (98 msgs, 40.20 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Theatres.Middle East   (959 msgs, 249.56 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Theatres.North   (129 msgs, 75.73 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Theatres.South   (576 msgs, 390.67 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.EMEAR.Theatres.UKI &- Vodafone   (135 msgs, 23.56 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Emerging Markets   (44 msgs, 10.54 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Emerging Markets.Central Engineering   (443 msgs, 66.24 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Emerging Markets.Emerging   (161 msgs, 91.72 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Emerging Markets.Large Opportunity Team   (22 msgs, 1.11 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Emerging Markets.SC&-C   (50 msgs, 8.37 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Emerging Markets.SP 3_0   (61 msgs, 21.14 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.ISG   (36 msgs, 12.87 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting   (533 msgs, 98.99 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.555555 PM AS-F Wendy Gould   (3 msgs, 0.10 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.555555 PM Andrzej   (5 msgs, 0.19 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.555555 PM Russia   (18 msgs, 1.52 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.726090 Advisory   (17 msgs, 5.72 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.729795 Advisory Israel   (1 msgs, 0.30 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.735134 Intact   (1 msgs, 0.04 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.748584 Nationwide NetApp   (1 msgs, 0.16 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.750933 CoputaCentre   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.753070 EDF   (5 msgs, 0.21 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 Advisory Emerging   (9 msgs, 2.53 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 HTOM Saudi   (6 msgs, 0.37 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 Ian Musgrave   (10 msgs, 0.29 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 NCE DV Sec Cleared Nicola Frye   (22 msgs, 0.81 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 NCE DV Sec Cleared Peter Barras   (10 msgs, 0.19 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 NCE UC Germany   (11 msgs, 0.55 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 NCE WLAN   (1 msgs, 0.12 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 PM PS Germany   (11 msgs, 0.91 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 PM Paul Tulley   (9 msgs, 0.25 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 PM South Africa for Nokwanda Sunduza   (7 msgs, 0.18 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 PM UKI cleared *** Alistair Cole ***   (10 msgs, 0.83 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 PM extension South Africa *** Luis Costa ***   (6 msgs, 0.38 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 PM extension South Africa *** Paul Bisogno ***   (22 msgs, 4.30 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 555555 WLAN NCE   (8 msgs, 8.35 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 703350   (4 msgs, 0.13 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 711362   (9 msgs, 0.74 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 711362 NCE BWI   (11 msgs, 0.34 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 717738   (10 msgs, 0.61 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 730714 for Etihad   (60 msgs, 27.66 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 730714 for eSharp   (32 msgs, 7.22 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 735674 (742289) Finanz   (13 msgs, 0.65 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 736022   (14 msgs, 0.48 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 738568   (4 msgs, 0.11 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 741181   (23 msgs, 1.84 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 747577 BASF UC   (6 msgs, 0.62 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 748584   (12 msgs, 0.50 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 748584 Nationwide Citrix   (5 msgs, 0.44 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 748987   (26 msgs, 1.87 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 749244   (12 msgs, 7.01 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 749316   (8 msgs, 2.35 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 749799   (11 msgs, 1.32 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 749799 Aramco   (12 msgs, 0.67 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 752237 BWI   (7 msgs, 0.18 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 752335 Sberbank NOS   (6 msgs, 1.02 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 753078   (11 msgs, 1.02 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.A 753953 Deutsche Bahn CAP   (6 msgs, 0.26 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Advanced Services Archives.Subcontracting.D 744304   (7 msgs, 0.17 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Business Development   (7 msgs, 1.07 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.AMERICAS   (52 msgs, 15.62 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.AMERICAS.US PS   (6 msgs, 0.06 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.APJC   (1 msgs, 0.12 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.EMEAR   (13 msgs, 1.13 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP   (252 msgs, 398.89 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR   (10 msgs, 1.52 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.Cable Media &- Video   (9 msgs, 0.32 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.Central   (23 msgs, 1.94 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.DT   (34 msgs, 3.67 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.EMEAR Strategy &- Planning   (15 msgs, 24.67 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.Emerging   (22 msgs, 0.67 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.Inbound - Outbound   (3 msgs, 0.12 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.Italy &- Med   (9 msgs, 0.45 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.North   (37 msgs, 3.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.Orange   (5 msgs, 0.05 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.Russia   (47 msgs, 16.26 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.Saudi   (18 msgs, 1.10 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.South   (12 msgs, 1.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.UKI   (7 msgs, 0.18 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.EMEAR.Vodafone   (27 msgs, 2.32 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives   (33 msgs, 45.38 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Drive Inclusion &- Diversity   (95 msgs, 73.83 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Services Portfolio   (87 msgs, 213.04 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Services Portfolio.Escape Velocity   (33 msgs, 36.84 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Transform   (106 msgs, 101.14 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Transform.Cognizant   (3 msgs, 5.30 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Transform.The Big Battle   (10 msgs, 1.49 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Transform.The Big Battle.CCS   (13 msgs, 2.62 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Transform.The Big Battle.Data Analytics   (54 msgs, 32.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Transform.The Big Battle.IoE   (68 msgs, 23.95 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Transform.The Big Battle.IoE.Indus   (113 msgs, 189.72 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.Transition   (8 msgs, 0.98 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Initiatives.VSEM   (138 msgs, 270.11 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Solution Team   (18 msgs, 3.57 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Solution Team.NGEN Prototype   (15 msgs, 1.89 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Solution Team.Network Transformation   (34 msgs, 18.08 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.Solution Team.vMS   (54 msgs, 10.58 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.System Integration Team   (2 msgs, 1.52 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Customer Transformation Team.GSP.System Integration Team.Project Support Office   (2 msgs, 0.40 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Emerging Technologies &- Innovations   (5 msgs, 0.73 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Global Project Management Office   (33 msgs, 17.84 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery   (198 msgs, 53.87 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures.CNS   (5 msgs, 5.41 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures.CNS.Core   (107 msgs, 43.83 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures.CNS.Data Centre   (19 msgs, 3.58 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures.CNS.Mobility   (1 msgs, 0.08 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures.CNS.SP Video   (2 msgs, 0.16 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures.SICS   (1 msgs, 0.06 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures.SICS.Collaboration   (157 msgs, 39.20 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures.SICS.Security   (2 msgs, 0.05 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Architectures.Validation   (8 msgs, 0.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Programs   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Programs.Acquisitions   (3 msgs, 3.97 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Programs.Business Development Management   (244 msgs, 72.15 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Programs.Project Management Office   (37 msgs, 4.88 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Programs.Project Support Office   (17 msgs, 1.44 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Innovation and Delivery.Programs.Project Support Office.Requests   (2512 msgs, 232.85 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Advanced Services.Partners   (231 msgs, 50.10 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Services Sales   (81 msgs, 9.95 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Services Sales.EMEAR   (127 msgs, 25.14 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Services Sales.EMEAR.Enterprise   (1 msgs, 0.05 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Services Sales.Emerging Customer Advocacy   (38 msgs, 1.23 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Services Sales.Emerging Customer Advocacy.Solutions Team   (75 msgs, 15.64 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Technical Services   (67 msgs, 24.36 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Archives.Technical Services.RMS   (11 msgs, 0.75 MB)

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Global CX Centers   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Global CX Centers.Advanced Delivery Network   (4 msgs, 23.16 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Global CX Centers.Advanced Delivery Network.Global Delivery Centre   (715 msgs, 428.06 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Global CX Centers.Cloud and Managed Services   (19 msgs, 2.30 MB)

srcfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Global CX Centers.Advanced Delivery Network.Global Delivery Centre"
dstfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Global CX Centers.Advanced Delivery Network"
echo "$srcfolder:$destfolder" > map.txt
./imapcopy.pl -v -C -R -M map.txt -S $server -D $server -m "${srcfolder}"

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations   (9 msgs, 0.63 MB)

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management   (397 msgs, 409.88 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Affordability &- Targets   (600 msgs, 446.58 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock   (863 msgs, 492.27 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Interlock v2   (15 msgs, 1.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Monthly Budget   (13 msgs, 7.90 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Monthly Budget.Feb'17 interlock   (130 msgs, 38.49 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Monthly Budget.Feb'18 interlock   (148 msgs, 144.86 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Monthly Budget.Jun'17 interlock   (74 msgs, 16.19 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Monthly Budget.Mar'17 interlock   (182 msgs, 57.94 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Monthly Budget.Mar'18 interlock   (21 msgs, 10.21 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Monthly Budget.May'17 interlock   (64 msgs, 75.84 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Quarterly Interlock   (16 msgs, 1.53 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Quarterly Interlock.Q1'18 interlock   (225 msgs, 353.25 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Quarterly Interlock.Q3'17 interlock   (313 msgs, 226.04 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Quarterly Interlock.Q4'17 Interlock   (211 msgs, 365.41 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Quarterly Interlock.Q4'18 Interlock   (16 msgs, 4.47 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management.Interlock.Steering Committee   (57 msgs, 29.60 MB)

srcfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Budget Management"
dstfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management"
echo "$srcfolder:$destfolder" > map.txt
./imapcopy.pl -v -C -R -M map.txt -S $server -D $server -m "${srcfolder}"

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY12 planning   (39 msgs, 28.97 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY12 planning.EMEA integration   (19 msgs, 1.86 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY12 planning.Ent - SP split   (1014 msgs, 431.37 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY14 planning   (1250 msgs, 790.14 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY15 planning   (588 msgs, 554.01 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY16 planning   (530 msgs, 788.96 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY16 planning.FY16 LRSP   (974 msgs, 1303.20 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY16 planning.GMV   (16 msgs, 10.58 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY17 planning   (1168 msgs, 1243.41 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY18 planning   (93 msgs, 156.32 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials.FY &- Long Range Planning.FY19 planning   (33 msgs, 64.15 MB)

srcfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Financials"
dstfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Financials"
echo "$srcfolder:$destfolder" > map.txt
./imapcopy.pl -v -C -R -M map.txt -S $server -D $server -m "${srcfolder}"

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services   (515 msgs, 165.77 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks   (407 msgs, 159.97 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.AMER   (1069 msgs, 127.41 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.AMER.USPS   (406 msgs, 39.48 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.APJC   (299 msgs, 38.93 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.Asks - Archives   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.Asks - Archives.CNS   (942 msgs, 122.93 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.Asks - Archives.GPMO   (468 msgs, 49.03 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.Asks - Archives.GSP   (859 msgs, 147.86 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.Asks - Archives.SICS   (271 msgs, 26.19 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.EMEAR   (480 msgs, 88.66 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.ET&-I   (161 msgs, 21.87 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.Global CX Centers   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.Global CX Centers.ADC   (336 msgs, 98.19 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Asks.OVH   (1247 msgs, 162.12 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.HiringSpace approvals   (1248 msgs, 79.53 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Process   (1242 msgs, 413.80 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Process.Contracted Services Process   (6 msgs, 3.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Process.Requisitions Process   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Process.Requisitions Process.Q4 exception   (166 msgs, 190.66 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services.Reports   (526 msgs, 545.56 MB)

srcfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Headcounts - Requisitions - Contracted Services"
dstfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Headcounts - Requisitions - Contracted Services"
echo "$srcfolder:$destfolder" > map.txt
./imapcopy.pl -v -C -R -M map.txt -S $server -D $server -m "${srcfolder}"

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects   (968 msgs, 203.97 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.Consumption   (1 msgs, 9.87 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.FY'13 rates   (230 msgs, 104.34 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.FY'14 rates   (220 msgs, 29.47 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.FY'15 rates   (66 msgs, 12.57 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.FY'16 rates   (399 msgs, 94.84 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.FY'17 rates   (145 msgs, 32.29 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.FY'18 rates   (33 msgs, 4.73 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.FY'19 rates   (21 msgs, 21.40 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.Project Green   (66 msgs, 49.89 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.Rates   (71 msgs, 21.51 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.T&-E   (54 msgs, 7.83 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects.Value selling   (91 msgs, 10.69 MB)

srcfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Oracle Projects"
dstfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Oracle Projects"
echo "$srcfolder:$destfolder" > map.txt
./imapcopy.pl -v -C -R -M map.txt -S $server -D $server -m "${srcfolder}"

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.Engagement Process.Commercial Offer   (44 msgs, 24.07 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.Engagement Process.Sales optimization - xxx   (6 msgs, 3.57 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.Services Collaboration Comittee   (45 msgs, 2.80 MB)

srcfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.Sales Strategy"
dstfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Sales Strategy"
echo "$srcfolder:$destfolder" > map.txt
./imapcopy.pl -v -C -R -M map.txt -S $server -D $server -m "${srcfolder}"

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.The Program.Delivery Management Office.Excellence.CAP and escalations   (60 msgs, 3.49 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.The Program.Delivery Management Office.Excellence.Colouring the picture   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.The Program.Delivery Management Office.Excellence.Governance   (12 msgs, 15.63 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.The Program.Delivery Management Office.Excellence.Metrics - KPI   (32 msgs, 12.90 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.The Program.Delivery Management Office.Genesis   (237 msgs, 180.05 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.The Program.Proposal   (87 msgs, 167.81 MB)

srcfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management Office.The Program"
dstfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.The Program"
echo "$srcfolder:$destfolder" > map.txt
./imapcopy.pl -v -C -R -M map.txt -S $server -D $server -m "${srcfolder}"

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management.Sales Strategy.Pricing &- Tools.Pricing Tools   (0 msgs, 0.00 MB)

srcfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Budget Management"
dstfolder="Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management"
echo "$srcfolder:$destfolder" > map.txt
./imapcopy.pl -v -C -R -M map.txt -S $server -D $server -m "${srcfolder}"

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Contracted Services   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Financials   (486 msgs, 610.38 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Financials.Cost   (3 msgs, 0.04 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Financials.Cost.PCOGS   (126 msgs, 59.90 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Financials.Cost.SCOGS   (46 msgs, 32.02 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Financials.FY &- Long Range Planning   (23 msgs, 1.76 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Financials.Forecasting   (383 msgs, 262.97 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Financials.Revenue   (15 msgs, 1.83 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Financials.Revenue.BNI   (88 msgs, 68.40 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Resource Alignment   (104 msgs, 18.48 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Sales Strategy   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Sales Strategy.Market Segmentation   (142 msgs, 268.31 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Sales Strategy.Presales Investments   (237 msgs, 82.50 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Sales Strategy.Pricing &- Tools   (715 msgs, 58.31 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.Sales Strategy.Pricing &- Tools.Pricing Tools   (4023 msgs, 529.44 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.The Program   (43 msgs, 39.27 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.The Program.Communication and Jive Page   (122 msgs, 47.37 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.The Program.Delivery Management Office   (293 msgs, 189.25 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.The Program.Excellence   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.The Program.GDC partnership   (3 msgs, 0.02 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Budget Management.The Program.Genesis   (237 msgs, 180.05 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Global Planning and Transformation.Team Stuff   (0 msgs, 0.00 MB)

# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio   (246 msgs, 282.70 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.2Tier   (23 msgs, 4.22 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.3rd party support   (3 msgs, 8.29 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.ARchitectural Transactional Service -ARTS-   (1 msgs, 0.01 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.AS 5_0 - AS-S - Subscription   (76 msgs, 35.92 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.AS Configurable   (115 msgs, 27.77 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.AS Fixed   (1973 msgs, 247.08 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.AS Video - Scientific Atlanta   (36 msgs, 9.14 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.ASk the PM   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.ASpect   (139 msgs, 36.52 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Axioss   (1 msgs, 0.52 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Broadhop   (2 msgs, 7.83 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Business Critical Services   (14 msgs, 2.23 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Collaboration Services   (40 msgs, 13.08 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Combined Day 2 - Operate Outcomes   (4 msgs, 0.87 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Combined Services   (199 msgs, 61.02 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Combined Services.Smart Operate   (17 msgs, 2.86 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.EnergyWise (JouleX)   (18 msgs, 20.39 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Escape Velocity   (33 msgs, 36.84 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.FTS   (27 msgs, 5.05 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Heartbeat - New Product Introduction   (32 msgs, 1.36 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.IC Nuggets   (6 msgs, 0.75 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.IronPort   (4 msgs, 0.04 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.LCA   (140 msgs, 19.40 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Modular Simplified Portfolio   (46 msgs, 3.78 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.NDS   (8 msgs, 0.16 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.NewScale   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Outcome Based   (10 msgs, 42.84 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Portcullis   (298 msgs, 85.47 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.ServiceGrid   (178 msgs, 44.50 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Services Model   (1 msgs, 0.03 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.SolveDirect   (2 msgs, 0.01 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Starent   (58 msgs, 10.57 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Tandberg   (90 msgs, 12.47 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Tidal   (21 msgs, 1.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.Vital Signs   (12 msgs, 0.94 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Product Management &- Portfolio.WebEx   (73 msgs, 40.39 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Strategy &- Planning   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff   (1025 msgs, 324.27 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Business Continuity Plan   (179 msgs, 32.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Business Review   (677 msgs, 800.90 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Business Review.Ops Review   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Business Review.Quarterly Business Review   (30 msgs, 43.53 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Cisco International   (232 msgs, 45.45 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Cust Sat   (156 msgs, 129.29 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Dashboards &- Scorecards   (138 msgs, 79.94 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Dashboards &- Scorecards.Customer   (23 msgs, 5.60 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Dashboards &- Scorecards.Executive Dashboard   (391 msgs, 168.55 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Dashboards &- Scorecards.Install Base   (20 msgs, 28.21 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Dashboards &- Scorecards.MBOs   (193 msgs, 197.77 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Dashboards &- Scorecards.Metrics   (97 msgs, 119.39 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Dashboards &- Scorecards.One Account View   (127 msgs, 131.52 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Dashboards &- Scorecards.Reporting   (272 msgs, 246.53 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Dashboards &- Scorecards.SCI - SPI   (28 msgs, 1.84 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Global Deal Hub   (47 msgs, 4.31 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Hierarchies   (394 msgs, 120.46 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Hierarchies.FY14 finances   (313 msgs, 90.28 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Hierarchies.FY14 people   (160 msgs, 19.21 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Hierarchies.FY15 hierarchies   (2 msgs, 0.33 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Hierarchies.FY16 hierarchies   (21 msgs, 3.17 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Hierarchies.FY17 hierarchies   (127 msgs, 100.17 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Hierarchies.FY18 hierarchies   (2 msgs, 2.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.ISO   (201 msgs, 68.21 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Organization   (4277 msgs, 2322.24 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges   (9 msgs, 0.63 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Cisco AS Optimization   (160 msgs, 138.67 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Contracted Services Q2'18   (70 msgs, 40.77 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Cost saving actions   (14 msgs, 8.01 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Deloitte support team   (14 msgs, 0.53 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.H2FY15   (376 msgs, 341.59 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.H2FY16   (27 msgs, 36.28 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.IoE moves   (72 msgs, 13.89 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Limited Restructuring   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Practices allocation   (26 msgs, 6.01 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Q1FY16   (6 msgs, 0.63 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.RB reduction   (4 msgs, 2.43 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Red To Blue Conversion   (98 msgs, 15.49 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Reqs   (10 msgs, 12.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Revenue war room Q2FY17   (19 msgs, 11.32 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Revenue war room Q3'17   (3 msgs, 0.08 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Revenue war room Q4'17   (5 msgs, 3.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.SCOGS &- residuals   (12 msgs, 15.85 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.Spending Freeze   (32 msgs, 22.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.P&-L challenges.id8   (1 msgs, 0.10 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Tools   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Tools.Delivery Collaboration Portal   (79 msgs, 37.52 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Team Stuff.Tools.Oracle Project   (208 msgs, 100.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development   (46 msgs, 13.14 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Governance   (632 msgs, 516.27 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Governance.Affordability   (34 msgs, 38.45 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process   (51 msgs, 9.12 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.AS-T Tracker   (15 msgs, 2.72 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.AScend   (18 msgs, 13.69 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.ASis   (31 msgs, 1.61 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.ASopt   (7 msgs, 3.87 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.Engagement Process   (241 msgs, 126.93 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.Engagement Process.2 Tier   (80 msgs, 8.91 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.GET   (17 msgs, 2.11 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.Kaizen2   (11 msgs, 4.73 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Business Development.Methodology &- Process.SPIFF   (1 msgs, 2.67 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.Business tagging   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.Business tagging.Product Codes   (379 msgs, 55.32 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.Business tagging.Technology tagging   (58 msgs, 38.59 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.PID Request   (1215 msgs, 160.67 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.PID Request.Delivery Groups   (6 msgs, 0.30 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.Pricing Strategy   (115 msgs, 78.48 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.Pricing Tools - new   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.Pricing Tools - new.AS Estimator   (8 msgs, 0.54 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.Pricing Tools - new.AS-Fixed   (1 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools - new.Statement of Work   (28 msgs, 15.40 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools.Pricing Tools - new.AS Pricing Tool for Subscription   (1042 msgs, 94.14 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Transformation and Planning.Budget Management Office.Sales Strategy.Pricing &- Tools.Pricing Tools.AS-T Quoter.Risk Assesment   (7 msgs, 0.25 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office   (248 msgs, 163.52 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.CAP management   (16 msgs, 1.29 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.Capacity Planning and Management   (57 msgs, 51.96 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.Cost to Serve   (16 msgs, 22.16 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.Cross Theatre   (34 msgs, 1.44 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.Master Schedule   (646 msgs, 240.95 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.Opportunity Management   (2 msgs, 0.24 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.R1024291 WfM BOM Capacity Planning   (23 msgs, 3.76 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.Resource Request Tool   (3013 msgs, 150.01 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.Skills   (78 msgs, 56.96 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.Time Reporting   (37 msgs, 10.45 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Operations and Renewals.Global Business Operations.Workforce Management Office.Utilization   (1 msgs, 0.02 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Platforms - Brett Wingo   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Product Management   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Strategy &- Portfolio   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Team Stuff   (71 msgs, 34.98 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Team Stuff.Leadership   (672 msgs, 1524.65 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Team Stuff.Leadership.Mexico City - Apr 24, 2018   (42 msgs, 98.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Team Stuff.V2MOM   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Team Stuff.VSEM   (6 msgs, 22.58 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Hierarchies Simplification   (101 msgs, 185.22 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Hierarchies Simplification.Offers - Architectures   (1 msgs, 0.03 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Hierarchies Simplification.P&-L and Financial Hierarchy   (1039 msgs, 576.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Hierarchies Simplification.P&-L and Financial Hierarchy.reporting   (90 msgs, 167.40 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Organization   (14 msgs, 23.77 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Organization.AMER L2   (4 msgs, 13.35 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Organization.CGEM accounts   (96 msgs, 35.19 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Organization.Delivery Integration   (98 msgs, 58.86 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Organization.Overhead   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Organization.Partner Management   (21 msgs, 6.41 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .AS Organization.Services Management   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .Ease of Selling   (9 msgs, 0.98 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .Renewals   (2 msgs, 6.34 MB)
# Professional.Cisco Systems.Customer eXperience (Cisco Services).Transformation Office - Jose van Dijk .Services One (FF-PSA)   (24 msgs, 22.70 MB)
# Professional.Cisco Systems.Laurent Burais   (2937 msgs, 349.18 MB)
# Professional.Cisco Systems.Laurent Burais.Car   (299 msgs, 54.42 MB)
# Professional.Cisco Systems.Laurent Burais.Management   (122 msgs, 50.21 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings   (84 msgs, 26.82 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.AS EM FY11 All Hands - Oct 19-20 2010   (18 msgs, 2.51 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.AS EMEAR All Managers   (60 msgs, 64.46 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Bangalore May 28-31, 2018   (14 msgs, 3.56 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.FY14 SLX Forum   (8 msgs, 0.57 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.FY15 SLX Forum   (15 msgs, 0.71 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.FY16 SLX Forum   (4 msgs, 0.05 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.London - November 9-10, 2015   (14 msgs, 7.38 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Offsite - Seattle Feb 26-28, 2018   (28 msgs, 9.06 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Offsite - Seattle Nov 13-16   (1 msgs, 0.06 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Presales - Frankfurt - May 6, 2013   (11 msgs, 1.77 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.SPF and FY16 planning - San Jose - January 21-21, 2015   (50 msgs, 111.91 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.SWES workshop - Lisbon - February 10-12, 2015   (20 msgs, 4.65 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Services Summit 2010   (22 msgs, 3.48 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Services Summit 2011 - Jun 8-9 2011   (34 msgs, 4.41 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Team Meeting - London - January 22-23, 2014   (14 msgs, 5.10 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Team Meeting - London - July 26-30 2010   (48 msgs, 25.66 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Team Meeting - London - July 7-8, 2014   (4 msgs, 0.54 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Team Meeting - London - June 11-12, 2013   (2 msgs, 0.01 MB)
# Professional.Cisco Systems.Laurent Burais.Meetings.Team Meeting - London - September 21-25, 2015   (41 msgs, 9.79 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives   (32 msgs, 3.22 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.ADN Transformation   (263 msgs, 190.84 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Ciscosson   (28 msgs, 3.57 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Customer eXperience setup   (77 msgs, 20.53 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.FASTS   (194 msgs, 63.96 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.H1 Prime   (12 msgs, 4.91 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.STEP   (29 msgs, 7.39 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution   (848 msgs, 1120.75 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Delivery   (421 msgs, 407.89 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Delivery.Delivery Optimization   (557 msgs, 242.93 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Delivery.Evolution 4 Outcomes   (2 msgs, 7.18 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Delivery.GDC Partner Initiative   (32 msgs, 14.88 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Relationship   (164 msgs, 213.48 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Relationship.Dashboard   (148 msgs, 107.90 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Relationship.SDE Playbook   (70 msgs, 143.40 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Relationship.SDE evolution   (253 msgs, 313.85 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Relationship.SIA role   (29 msgs, 19.78 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Customer Relationship.SSM evolution   (14 msgs, 16.57 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Operating Model   (289 msgs, 306.00 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Operating Model.Evolution 4 Outcomes   (2 msgs, 7.18 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Services Evolution.Operating Model.GDC Partner Initiative   (32 msgs, 14.88 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Strategic Promises   (223 msgs, 97.32 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Transform   (106 msgs, 101.14 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Transform.Cognizant   (3 msgs, 5.30 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Transform.The Big Battle   (10 msgs, 1.49 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Transform.The Big Battle.CCS   (13 msgs, 2.62 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Transform.The Big Battle.Data Analytics   (54 msgs, 32.69 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Transform.The Big Battle.IoE   (84 msgs, 24.56 MB)
# Professional.Cisco Systems.Laurent Burais.My Initiatives.Transform.The Big Battle.IoE.Indus   (113 msgs, 189.72 MB)
# Professional.Cisco Systems.Laurent Burais.My Team   (1 msgs, 0.04 MB)
# Professional.Cisco Systems.Laurent Burais.My Team.Tyler Price   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Laurent Burais.My Team.Yvonne Ware   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Laurent Burais.Positions   (7 msgs, 0.11 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office   (3 msgs, 0.10 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Collaboration   (23 msgs, 1.27 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Education   (6 msgs, 0.41 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Education.Bundles - Refresher   (1 msgs, 7.87 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Business Transformation   (33 msgs, 15.86 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Business Transformation.Manage -Dawn Beech-   (2 msgs, 0.45 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Business Transformation.Organizational Development -Cintya Robles-   (18 msgs, 2.69 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Business Transformation.Reporting -Susanne Nielsen-   (123 msgs, 55.57 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Business Transformation.Resource Management -Jerker Akesson-   (40 msgs, 19.07 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Business Transformation.Resource To Close -Laurent Burais-   (2 msgs, 0.01 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.FY11   (1 msgs, 0.01 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.GSP - Operations   (9 msgs, 0.63 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Investments   (1 msgs, 0.11 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Management calls   (36 msgs, 4.34 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Management calls.Integrated Business Review   (220 msgs, 167.44 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Ops review   (4 msgs, 58.81 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Overdelivery   (36 msgs, 18.15 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.People   (61 msgs, 20.10 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.People.Cisco Skills Inventory   (4 msgs, 2.10 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.People.Project Management   (5 msgs, 0.45 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.People.Project Management.Assignment playbook   (15 msgs, 6.80 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.People.Pulse Survey   (43 msgs, 37.02 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.People.ePM - Bonus - Talent review   (5 msgs, 10.10 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Tools   (22 msgs, 11.04 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together   (13 msgs, 5.16 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.Customer Satisfaction   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.Customer Satisfaction.Delivery Process Management -Nicole Finger-   (1 msgs, 0.02 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.Flexible Workforce - Resourcing   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.Flexible Workforce - Resourcing.Capacity Model -Elisa Ouellette-   (7 msgs, 1.50 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.People Development - Management Effectiveness   (2 msgs, 0.20 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.People Development - Management Effectiveness.Reward and Recognition   (29 msgs, 1.74 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.People Development - Management Effectiveness.Roles - Responsibilities   (8 msgs, 1.66 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.Profitability   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.Profitability.8-Quarter Rolling Plan -Ratan Agarwal-   (65 msgs, 54.55 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.Profitability.As Sold Margin   (36 msgs, 15.78 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Transform Together.Profitability.Tools Monetization   (27 msgs, 3.37 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Emerging Markets Operations.Web site - Wiki   (1 msgs, 0.07 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Process   (22 msgs, 22.27 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Process.Complex Deals   (2 msgs, 0.04 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Business Development Office.Process.Subscription   (270 msgs, 165.50 MB)
# Professional.Cisco Systems.Laurent Burais.Positions.Senior Planning Manager   (68 msgs, 1.14 MB)
# Professional.Cisco Systems.Laurent Burais.Training   (389 msgs, 128.86 MB)
# Professional.Cisco Systems.Laurent Burais.Travel   (490 msgs, 13.29 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis   (1776 msgs, 195.97 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.2012 move   (1172 msgs, 159.11 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Events   (150 msgs, 73.43 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Events.GSX11 - Aug 31-Sep 2 2010   (138 msgs, 13.67 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Events.GSX11 - Aug 31-Sep 2- 2010   (104 msgs, 7.93 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Events.GSX12 - Aug 29-Sep 2 2011   (116 msgs, 8.63 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Events.GSX13 - Aug 28-29 2012   (78 msgs, 5.49 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Events.GSX14   (5 msgs, 0.08 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Events.Laurent Blanchard - Jan 25 2011   (205 msgs, 23.48 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Events.Social Action Day - Dec 16 2009   (8 msgs, 0.40 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Events.TelePresence Launch - Mar 19 2010   (35 msgs, 16.46 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board   (148 msgs, 28.53 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board.Communication   (126 msgs, 3.84 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board.Communication.Girls   (82 msgs, 30.57 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board.Communication.Green   (7 msgs, 0.49 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board.Communication.Mission Handicap   (4 msgs, 7.81 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board.Communication.More Together   (3 msgs, 0.35 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board.Communication.Plan Social   (207 msgs, 70.98 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board.Communication.Senior   (114 msgs, 24.68 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board.External Relationship   (61 msgs, 7.62 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Sophia Board.France Leaders   (75 msgs, 26.47 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Workplace   (647 msgs, 69.46 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Workplace.ERT   (139 msgs, 17.81 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Workplace.Infrastructure   (743 msgs, 78.52 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Workplace.Lab   (588 msgs, 107.33 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Workplace.Lobby ambassador   (16 msgs, 2.91 MB)
# Professional.Cisco Systems.Nice Sophia Antipolis.Workplace.Telepresence   (676 msgs, 61.13 MB)
# Professional.Cisco Systems.Talent &- People   (209 msgs, 45.68 MB)
# Professional.Cisco Systems.Talent &- People.CPC - ePM - Bonus - Talent review   (24 msgs, 7.23 MB)
# Professional.Cisco Systems.Talent &- People.Inclusion &- Diversity   (2 msgs, 4.96 MB)
# Professional.Cisco Systems.Talent &- People.People   (663 msgs, 39.74 MB)
# Professional.Cisco Systems.Talent &- People.People Planning   (76 msgs, 109.73 MB)
# Professional.Cisco Systems.Talent &- People.People.Anita Smillie   (109 msgs, 3.25 MB)
# Professional.Cisco Systems.Talent &- People.People.Anneliese Rhodes   (84 msgs, 22.57 MB)
# Professional.Cisco Systems.Talent &- People.People.Arnaud Godet   (53 msgs, 9.32 MB)
# Professional.Cisco Systems.Talent &- People.People.Carsten Cramme   (16 msgs, 0.60 MB)
# Professional.Cisco Systems.Talent &- People.People.Christina Donovan   (20 msgs, 3.26 MB)
# Professional.Cisco Systems.Talent &- People.People.Cintya Robles-Fernandez   (20 msgs, 0.26 MB)
# Professional.Cisco Systems.Talent &- People.People.Dawn Beech   (121 msgs, 17.20 MB)
# Professional.Cisco Systems.Talent &- People.People.Eliana NEGRISOLI   (4 msgs, 0.25 MB)
# Professional.Cisco Systems.Talent &- People.People.Eugene Chomiak   (17 msgs, 2.15 MB)
# Professional.Cisco Systems.Talent &- People.People.Fabio Ruzzolini   (13 msgs, 0.12 MB)
# Professional.Cisco Systems.Talent &- People.People.Georgina Blane   (3 msgs, 0.65 MB)
# Professional.Cisco Systems.Talent &- People.People.Hector Acevedo   (13 msgs, 0.31 MB)
# Professional.Cisco Systems.Talent &- People.People.Hiring   (0 msgs, 0.00 MB)
# Professional.Cisco Systems.Talent &- People.People.Ingo Chudleigh-Lyle   (144 msgs, 20.71 MB)
# Professional.Cisco Systems.Talent &- People.People.Instant Messaging   (460 msgs, 5.83 MB)
# Professional.Cisco Systems.Talent &- People.People.Ivan Pashkevich   (4 msgs, 0.04 MB)
# Professional.Cisco Systems.Talent &- People.People.Jan Plender   (3 msgs, 0.01 MB)
# Professional.Cisco Systems.Talent &- People.People.Jared Hein   (8 msgs, 0.18 MB)
# Professional.Cisco Systems.Talent &- People.People.Jay Volk   (2 msgs, 0.01 MB)
# Professional.Cisco Systems.Talent &- People.People.Jerker Akesson   (23 msgs, 0.97 MB)
# Professional.Cisco Systems.Talent &- People.People.Juergen Gunter   (6 msgs, 1.13 MB)
# Professional.Cisco Systems.Talent &- People.People.Kamal Patel   (3 msgs, 0.01 MB)
# Professional.Cisco Systems.Talent &- People.People.Karen Melville   (3 msgs, 0.02 MB)
# Professional.Cisco Systems.Talent &- People.People.Karine SANTICCHI   (21 msgs, 1.87 MB)
# Professional.Cisco Systems.Talent &- People.People.Kevin Raak   (22 msgs, 2.45 MB)
# Professional.Cisco Systems.Talent &- People.People.Laxmi Mullapudi   (9 msgs, 0.08 MB)
# Professional.Cisco Systems.Talent &- People.People.Les Brand   (7 msgs, 0.11 MB)
# Professional.Cisco Systems.Talent &- People.People.Lia Marinos   (10 msgs, 0.40 MB)
# Professional.Cisco Systems.Talent &- People.People.MK Balachandran   (11 msgs, 0.35 MB)
# Professional.Cisco Systems.Talent &- People.People.Magdalena Knapczyk   (1 msgs, 0.03 MB)
# Professional.Cisco Systems.Talent &- People.People.Meena Gandhi   (9 msgs, 0.13 MB)
# Professional.Cisco Systems.Talent &- People.People.Natasa Vuckovic   (30 msgs, 1.23 MB)
# Professional.Cisco Systems.Talent &- People.People.Nikki Moberly   (15 msgs, 39.00 MB)
# Professional.Cisco Systems.Talent &- People.People.Rajesh Dixit   (19 msgs, 2.59 MB)
# Professional.Cisco Systems.Talent &- People.People.Raul Anton   (1 msgs, 0.04 MB)
# Professional.Cisco Systems.Talent &- People.People.Sameer Modak   (1 msgs, 0.00 MB)
# Professional.Cisco Systems.Talent &- People.People.